import Game from "@/game";
import { Bishop, King, Knight, Pawn, Queen, Rook } from "@/pieces";

describe("Game", () => {
  it("should set up pieces in starting positions", () => {
    const game = new Game();
    expect(game.state).toMatchObject(startingPositions);
  });
});

var startingPositions = {
  A1: new Rook("white", "A", 1),
  B1: new Knight("white", "B", 1),
  C1: new Bishop("white", "C", 1),
  D1: new Queen("white", "D", 1),
  E1: new King("white", "E", 1),
  F1: new Bishop("white", "F", 1),
  G1: new Knight("white", "G", 1),
  H1: new Rook("white", "H", 1),

  A2: new Pawn("white", "A", 2),
  B2: new Pawn("white", "B", 2),
  C2: new Pawn("white", "C", 2),
  D2: new Pawn("white", "D", 2),
  E2: new Pawn("white", "E", 2),
  F2: new Pawn("white", "F", 2),
  G2: new Pawn("white", "G", 2),
  H2: new Pawn("white", "H", 2),
  A3: null,
  B3: null,
  C3: null,
  D3: null,
  E3: null,
  F3: null,
  G3: null,
  H3: null,
  A4: null,
  B4: null,
  C4: null,
  D4: null,
  E4: null,
  F4: null,
  G4: null,
  H4: null,
  A5: null,
  B5: null,
  C5: null,
  D5: null,
  E5: null,
  F5: null,
  G5: null,
  H5: null,
  A6: null,
  B6: null,
  C6: null,
  D6: null,
  E6: null,
  F6: null,
  G6: null,
  H6: null,
  A7: new Pawn("black", "A", 7),
  B7: new Pawn("black", "B", 7),
  C7: new Pawn("black", "C", 7),
  D7: new Pawn("black", "D", 7),
  E7: new Pawn("black", "E", 7),
  F7: new Pawn("black", "F", 7),
  G7: new Pawn("black", "G", 7),
  H7: new Pawn("black", "H", 7),

  A8: new Rook("black", "A", 8),
  B8: new Knight("black", "B", 8),
  C8: new Bishop("black", "C", 8),
  D8: new Queen("black", "D", 8),
  E8: new King("black", "E", 8),
  F8: new Bishop("black", "F", 8),
  G8: new Knight("black", "G", 8),
  H8: new Rook("black", "H", 8),
};
